### ISSUE TITLE
Standalone support?

### ISSUE THREAD

**Issue by NAThompson** [boostorg/stacktrace#128]
How much effort would it be to support this library in standalone mode?

From a cursory glance, it appears that `boost/config` is used only to detect existence of `#pragma once`, but that seems easy enough to remove.

Essentially, we would like to use *just* this as a `git submodule`.

**Comment by ceztko** [comment]
Note to the author: pointing to other base library advancements that got standardized and offered a standalone version from the beginning, like [`date`](https://github.com/HowardHinnant/date) from Howard Hinnant or [`fmtlib`](https://github.com/fmtlib/fmt)  from Victor Zverovich shall not be an excuse for me or other people for not helping you in creating a standalone version of `stacktrace`, but quite frankly I want to say that having stuff standardized is one mean to reduce the dependency on big general purpose libraries such as boost, so I believe developing this with boost dependency from scratch was a mistake and it's just delaying the adoption of such helpful facility. I'm sure that many people coming here would love to use `stacktrace` today but will not because that would require importing boost for just a single feature.

**Comment by nigels-com** [comment]
Coud well be that a majority here are already widely boost-entangled.  So it isn't high on our priority list, but by the sound of it, would not be a complicated patch.

**Comment by apolukhin** [comment]
You could always try to make a standalone library by yourself ond/or provide a patch here
